### ISSUE TITLE
[Request] Select public teams when creating matches

### ISSUE THREAD

**Issue by stranden** [PhlexPlexico/G5V#100]
Hi,

Would it be possible to select team with the Public flag enabled, when creating a match:

![image](https://user-images.githubusercontent.com/18518722/151591854-ee7963e4-c154-425a-8bd9-4b98f3ba89cb.png)

Right now I'm importing the teams via the API with one specific user.
So it is only Admins which can create matches with teams from the imports.

We are specifically setting the Public flag so users shouldn't have admin rights.
You can see all the teams [here](https://routes.dk/teams)

**Comment by PhlexPlexico** [comment]
Okay latest image (once built) should have that up and running now :)

**Comment by stranden** [comment]
I have tested and it's working perfectly!
Thanks! :)
