### ISSUE TITLE
Best practice for updating old instance?

### ISSUE THREAD

**Issue by DigitalFriends** [PhlexPlexico/G5V#107]
Hi, congratulations to the stable version!

Been using G5V+API for a while, i'm looking to update both the frontend and api on Debian. 

Is there any written guide or something? I'm running everything in a VM, so i can snapshot before starting.

**Comment by PhlexPlexico** [comment]
Heya!

Depends on how you've installed it in the first place - if you've installed just by cloning the repo, you can just call `git pull`, followed by `yarn build` and replace wherever the old version is with the new files in the `dist` directory.

If you've used Docker, you can just pull the latest image.

If you're using docker-compose, I believe just calling `docker-compose up -d` should update the image, as well as G5API!

Thanks!

**Comment by DigitalFriends** [comment]
> Heya!
> 
> Depends on how you've installed it in the first place - if you've installed just by cloning the repo, you can just call `git pull`, followed by `yarn build` and replace wherever the old version is with the new files in the `dist` directory.
> 
> If you've used Docker, you can just pull the latest image.
> 
> If you're using docker-compose, I believe just calling `docker-compose up -d` should update the image, as well as G5API!
> 
> Oh, and for API it's simple! All you have to do is the following steps:
> 
> ```shell
> git pull
> # update dependencies
> yarn
> # update db
> yarn migrate-prod-upgrade
> # restart PM2 instance
> yarn restartprod
> ```
> 
> That should update the API :)
> 
> Thanks!

Wow, awesome! 

I just downloaded the releases and installed it barebones. I will give this a go tonight, thank you for this truly AWESOME project.

**Comment by PhlexPlexico** [comment]
Anytime! Yeah if you're downloading from releases you should just be able to overwrite the files and follow the same instructions (minus the git pulls).

And thanks! Glad you're finding some use out of it 😁

**Comment by DigitalFriends** [comment]
Hey, updating seems to be rather complicated. I'm running into alot of errors when running yarn (for updating the G5V), same with the API. 

I'm just considering doing a fresh install, since i would need to create 10+ issues to resolve all these errors!

**Comment by PhlexPlexico** [comment]
What are the errors you're exactly experiencing? 

I haven't made a release for the latest features here (login, etc) due to it being largely untested aside from me. I know there's a select few people that run based off of the master branch here. If you'd like, you could try just doing that, so when there's a new update you can simply `git pull` and then build based off that.

Updating shouldn't be too hard, as I've tried to streamline the process as much as possible. Example, for the front-end it's a 4 step process:
- Git pull latest changes
- Yarn install to update any packages
- yarn build to build for production
- Move files from the dist directory into wherever your web directory is.

For the API it's very similar, but since there's no web server needed it's only the following:
- git pull latest changes
- yarn install to update any packages
- yarn migrate-prod-upgrade to update the database
- yarn restartprod (if prod is currently running)

Downloading from releases isn't really encouraged if you wish to be on the bleeding edge, it's really not meant for being kept up-to-date with everything, but more of a tagging system for myself in order to keep track of what features were added when.

**Comment by DigitalFriends** [comment]
Hey, 

G5V worked perfectly fine, thank you for that!

However, the API is not going as smooth. 

Any idea on how to update node?

`yarn install
yarn install v1.22.5
[1/6] Validating package.json...
error g5api@1.5.0.0: The engine "node" is incompatible with this module. Expected version ">=14.18.1". Got "13.8.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
`

**Comment by PhlexPlexico** [comment]
I usually use `nvm` which is a version manager for node. If you've installed via `apt` I would recommend just using NVM

https://github.com/nvm-sh/nvm

Thanks!

**Comment by DigitalFriends** [comment]
On to the next issue, any idea what might cause this?



`
 yarn migrate-prod-upgrade
yarn run v1.22.5
$ db-migrate --env production --config config/production.json up:production
Ignoring invalid configuration option passed to Connection: driver. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
Ignoring invalid configuration option passed to Connection: redisHost. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
Ignoring invalid configuration option passed to Connection: redisPort. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
Ignoring invalid configuration option passed to Connection: redisTTL. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
Ignoring invalid configuration option passed to Connection: redisPass. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
[ERROR] Error: Data truncated for column 'knife_kills' at row 1
    at Packet.asError (/home/get5web/get5webnew/G5API/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/home/get5web/get5webnew/G5API/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/home/get5web/get5webnew/G5API/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/home/get5web/get5webnew/G5API/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/home/get5web/get5webnew/G5API/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/get5web/get5webnew/G5API/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
error Command failed with exit code 1.
`

**Comment by PhlexPlexico** [comment]
By any chance are you using a database that is already setup with the old get5-web?

**Comment by DigitalFriends** [comment]
> 

I am not sure, but i don't think so. I am fairly sure i made a clean install and followed the instructions carefully here on Github. 

95% sure that it's a new db since i made a new server for this project.

**Comment by DigitalFriends** [comment]
Ran this: 
yarn migrate-create-prod
yarn run v1.22.5
$ MYSQL_FLAGS="-CONNECT_WITH_DB" db-migrate --env production --config config/production.json db:create get5

Ignoring invalid configuration option passed to Connection: driver. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection

Ignoring invalid configuration option passed to Connection: redisHost. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection

Ignoring invalid configuration option passed to Connection: redisPort. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection

Ignoring invalid configuration option passed to Connection: redisTTL. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection

Ignoring invalid configuration option passed to Connection: redisPass. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection

[INFO] Created database "get5"
Done in 0.24s.

But when i ran the prod upgrade i ran into:

yarn migrate-prod-upgrade

yarn run v1.22.5
$ db-migrate --env production --config config/production.json up:production

Ignoring invalid configuration option passed to Connection: driver. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection

Ignoring invalid configuration option passed to Connection: redisHost. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection

Ignoring invalid configuration option passed to Connection: redisPort. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection

Ignoring invalid configuration option passed to Connection: redisTTL. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection

Ignoring invalid configuration option passed to Connection: redisPass. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection

[ERROR] Error: Duplicate column name 'util_damage'
    at Packet.asError (/home/get5web/get5webnew/G5API/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/home/get5web/get5webnew/G5API/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/home/get5web/get5webnew/G5API/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/home/get5web/get5webnew/G5API/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/home/get5web/get5webnew/G5API/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/get5web/get5webnew/G5API/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
error Command failed with exit code 1.

**Comment by PhlexPlexico** [comment]
Hah yeah, looks like there was an issue in creating the DB. So what you wanna do is the following:

- Drop the old  DB `yarn migrate-drop-prod`
- Create the new DB again `yarn migrate-create-prod`
- Run the migration scripts `yarn migrate-prod-upgrade`

That should work as intended.

**Comment by DigitalFriends** [comment]
The drop worked!

yarn migrate-drop-prod
[INFO] Deleted database "get5"
Done in 0.31s.

However, the create-prod did not 
yarn migrate-create-prod
yarn run v1.22.5

[ERROR] AssertionError [ERR_ASSERTION]: ifError got unwanted exception: Unknown database 'get5'

    at /home/get5web/get5webnew/G5API/node_modules/db-migrate/lib/commands/db.js:17:12
    at /home/get5web/get5webnew/G5API/node_modules/db-migrate/lib/driver/index.js:95:9
    at /home/get5web/get5webnew/G5API/node_modules/db-migrate-mysql/index.js:518:14
    at Connection.<anonymous> (/home/get5web/get5webnew/G5API/node_modules/mysql2/lib/connection.js:775:13)
    at Object.onceWrapper (events.js:520:26)
    at Connection.emit (events.js:400:28)
    at Connection._notifyError (/home/get5web/get5webnew/G5API/node_modules/mysql2/lib/connection.js:236:12)
    at ClientHandshake.<anonymous> (/home/get5web/get5webnew/G5API/node_modules/mysql2/lib/connection.js:125:14)
    at ClientHandshake.emit (events.js:412:35)
    at ClientHandshake.execute (/home/get5web/get5webnew/G5API/node_modules/mysql2/lib/commands/command.js:39:14)
    at Packet.asError (/home/get5web/get5webnew/G5API/node_modules/mysql2/lib/packets/packet.js:728:17)
    at ClientHandshake.execute (/home/get5web/get5webnew/G5API/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/home/get5web/get5webnew/G5API/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/home/get5web/get5webnew/G5API/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/home/get5web/get5webnew/G5API/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/get5web/get5webnew/G5API/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    
    error Command failed with exit code 1.

**Comment by PhlexPlexico** [comment]
Hmmm okay, that's a weird one. I think the easiest way is just to sudo into mysql and just do the following, then call `yarn migrate-prod-upgrade`

```sql
CREATE DATABASE GET5;
GRANT ALL PRIVILEGES ON get5.* TO '<get5_user>'@'localhost'; 
FLUSH PRIVILEGES;
```
Where `<get5_user>` is the user you defined in your `production.json`.

**Comment by DigitalFriends** [comment]
That worked perfectly, wow!

Thank you so much for the support, this was great.

**Comment by PhlexPlexico** [comment]
Anytime :) glad it's working for you now!
