### ISSUE TITLE
Order servers: My servers, My Public Servers, Other users public servers during match creation

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5V#111]
I have no idea if changing the order here: https://phlex.avidgamers.me/api/servers/available to have 

1. our servers that are not public to be the first
2. then our public servers 
3. and then others' public servers 

is wanted in any way, but I'd find it very useful. 

I think it is caused by something in here: https://github.com/PhlexPlexico/G5API/blob/master/routes/servers.js#L174

**Comment by PhlexPlexico** [comment]
Well the API doesn't bring back any type of ordering, aside from just returning what servers are available. So it should be up to the front end to sort these things for the end users. I'm not sure if I'll have time to work on this, but pull requests are always welcome. All that would have to be done is check if the `GetAllAvailableServers()` call returns an array of objects, then just call a sort function based on the array of objects. Shouldn't be too difficult I wouldn't think.

**Comment by kubo6472** [comment]
Too fast, thank you. 💯
