### ISSUE TITLE
[FR] Add public toggle to seasons

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5V#113]
Can there be added a toggle to set a season as public?

**Comment by PhlexPlexico** [comment]
This would actually need more API work, and I'm not sure if I would completely support it. If you're running multiple seasons and needing multiple people to access it, I would assume them to be admins more than anything.

**Comment by kubo6472** [comment]
Yea, I can imagine adding some tables to the DB. Okay, i will re-run the api with added admins. Thanks.
