### ISSUE TITLE
[Enhancement] Autorefresh veto

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5V#118]
I have no idea how one would implement this, but it would be really nice if veto on match page updated automatically.

**Comment by PhlexPlexico** [comment]
It's funny you mention this. I was looking into ways to pull data from the API. Eventually I would LOVE to setup something that would be able to connect via websockets, but that would be quite the amount of work to register (and I think I would have to rewrite a bunch of things). However, I did at one point try refreshing data from the API, but never got events emitting properly. Definitely something I want to look into though (provided I don't want to rewrite the entire front-end...).

Thanks for the suggestion and I'll look into it!
