### ISSUE TITLE
[BUG] Endless login loop (local login)

### ISSUE THREAD

**Issue by xe1os** [PhlexPlexico/G5V#125]
@PhlexPlexico if a user tries to login using Steam64 ID without registering, then the login goes into endless loop.

![image](https://user-images.githubusercontent.com/39219862/164341798-e4f6dde2-806b-4e18-a46e-c57cc2026cb6.png)

**Comment by PhlexPlexico** [comment]
Are you able to get the logs from the console? Last o tried it gives "invalid username or password".

**Comment by PhlexPlexico** [comment]
Looks like this was actually the API not returning a proper response. Fixed and is working as intended, good catch @xe1os :)

Thanks!
