### ISSUE TITLE
No matching Manifest Docker Compose

### ISSUE THREAD

**Issue by Iwhite67** [PhlexPlexico/G5V#131]
Hello, i use your docker-compose.yml and when i make docker-compose up, i have this error

i'm on Ubuntu 20.04
`
Pulling g5api (ghcr.io/phlexplexico/g5api:latest)...
latest: Pulling from phlexplexico/g5api
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
`

**Comment by Iwhite67** [comment]
yes, i make my test on freebox server
i don't have my prod serv on actualy :p

**Comment by PhlexPlexico** [comment]
That may be why then! That being said, I think the API may have troubles compiling since bcrypt has to be compiled during build... Maybe I'll try adding it, but I can't guarantee it'll work on that arch!

**Comment by Iwhite67** [comment]
i can try on my prod server but i have one question, is a problem to have caddy on same server of nginx ?

i have a server with nginx / mariadb / pterodactyl.

**Comment by Iwhite67** [comment]
Thanks you, i check this weekend.

**Comment by Iwhite67** [comment]
`
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.g5v: 'platform'
`

**Comment by PhlexPlexico** [comment]
Hmm you may have to bump the `version` at the top to `3` instead of `2`... Very odd, I guess it may not be able to build due to nginx not having that build file either. Very odd, indeed!

Thanks!

**Comment by Iwhite67** [comment]
`Starting get5db                ... done
Recreating caddy-reverse-proxy ... error
Starting G5API                 ...

ERROR: for caddy-reverse-proxy  Cannot start service caddy: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/root/get5/Caddyfile" to rootfs at "/etc/caddy/Caddyfile" caused: mount through procfd: not a directory: unknown: Are you trying to mount a direcStarting G5API                 ... done
`

`version: '2.1'

networks:
  get5:
    external: true

services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy-reverse-proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes: 
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - get5
    environment:
      - CADDY_URL=http://match.cs.white-gaming.fr
      - CADDY_API_ENDPOINT=api
      - CADDY_REVERSE_PROXY_PORT=3301
  
  get5db:
    image: yobasystems/alpine-mariadb
    container_name: get5db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=get5
      - MYSQL_USER=get5
      - MYSQL_PASSWORD=
    ports:
      - "3307:3306"
    networks:
      - get5

  g5api:
    image: ghcr.io/phlexplexico/g5api:latest
    depends_on:
      - get5db
    container_name: G5API
    volumes: 
      - redisVol:/RedisFiles
    expose:
      - 3301
    environment:
      - PORT=3301
      - HOSTNAME=http://match.cs.white-gaming.fr
      - DBKEY=
      - STEAMAPIKEY=
      - SHAREDSECRET=funzilat
      - CLIENTHOME=http://match.cs.white-gaming.fr
      - APIURL=http://match.cs.white-gaming.fr/api
      - SQLUSER=get5
      - SQLPASSWORD=
      - SQLPORT=3306
      - DATABASE=get5
      - SQLHOST=get5db
      - ADMINS=
      - SUPERADMINS=76561198033164185
      - REDISPASSWORD=
      - UPLOADDEMOS=true
    restart: unless-stopped
    networks:
      - get5

  g5v:
    image: ghcr.io/phlexplexico/g5v:latest
    depends_on: 
      - g5api
      - caddy
    container_name: G5V-Front-End
    restart: always
    networks:
      - get5

volumes:
  redisVol:
    external: false`

**Comment by Iwhite67** [comment]
- ./Caddyfile:/etc/caddy/Caddyfile
to
- ./Caddyfile:/etc/caddy/Caddyfile.conf 

fix

**Comment by Iwhite67** [comment]
so, i have website but problem with API

when i click on sign in

```server{
    # Port listen
    listen 80;

    # DNS Record for catch request
    server_name match.cs.white-gaming.fr;

    # Open block for process forward request
    location /{
        # Server where traffic is transferred
        proxy_pass http://172.18.0.4;
        # Include file proxy_params with general param
        include proxy_params;
    }

        location /api/* {
         proxy_pass http://172.18.0.5:3301;
        include proxy_params;
   }
}
```


![image](https://user-images.githubusercontent.com/9698964/165924499-234dc1c0-aeb5-4fe6-9498-5288ec6a3364.png)

**Comment by Iwhite67** [comment]
> Well, Caddy is effectively doing nothing if you have your NGINX doing all the proxy requests for you. Did you remove the depends in the g5v part of the docker file?
> 
> ```yaml
>   g5v:
>     image: ghcr.io/phlexplexico/g5v:latest
>     depends_on: 
>       - g5api
>       - caddy
> ```
> 
> Remove caddy from there and try building again, it should run without issue. then grab the IP addresses once more from the containers and update them in your nginx conf.

Same, i have access, but nothing when i click on sign in

**Comment by PhlexPlexico** [comment]
Vue isn't communicating because it can't find the reverse call for `/api/`. This either has to be done on nginx, or with the given Caddy reverse proxy, not both.

```
location /api/ {
                proxy_pass http://172.18.0.5:3301;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
        }
```

This block in your NGINX conf will have `https://match.cs.white-gaming.fr/api` -> `http://172.18.0.5:3301` which is your internal Docker IP and port that you assigned it. Make sure your API is running as well and nothing has caused it to crash - `docker container ls` and see if it's running.

**Comment by Iwhite67** [comment]
> Vue isn't communicating because it can't find the reverse call for `/api/`. This either has to be done on nginx, or with the given Caddy reverse proxy, not both.
> 
> ```
> location /api/ {
>                 proxy_pass http://172.18.0.5:3301;
>                 proxy_http_version 1.1;
>                 proxy_set_header Upgrade $http_upgrade;
>                 proxy_set_header Connection 'upgrade';
>                 proxy_set_header Host $host;
>                 proxy_cache_bypass $http_upgrade;
>         }
> ```
> 
> This block in your NGINX conf will have `https://match.cs.white-gaming.fr/api` -> `http://172.18.0.5:3301` which is your internal Docker IP and port that you assigned it. Make sure your API is running as well and nothing has caused it to crash - `docker container ls` and see if it's running.

G5API running
![image](https://user-images.githubusercontent.com/9698964/165959546-c20c248d-d20a-477b-8662-2854f9241648.png)

![image](https://user-images.githubusercontent.com/9698964/165959691-e0db1a31-0cfc-4bda-9802-1ae07f0a22b9.png)

```
server{
    # Port listen
    listen 80;

    # DNS Record for catch request
    server_name match.cs.white-gaming.fr;

    # Open block for process forward request
location / {
                proxy_pass http://172.18.0.4;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
        }

        location /api/ {
        proxy_pass http://172.18.0.5:3301;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
   }
}

```

**Comment by PhlexPlexico** [comment]
```
server{
    # Port listen
    listen 80;

    # DNS Record for catch request
    server_name match.cs.white-gaming.fr;

    # Open block for process forward request
location / {
                proxy_pass http://172.18.0.4;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
        }

        
}
location /api/ {
        proxy_pass http://172.18.0.5:3301;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
   }
```
The location /api/ cannot be inside the root location.

**Comment by Iwhite67** [comment]
sorry, i have not understand

**Comment by Iwhite67** [comment]
> Once again, please move `location /api/` outside of the `location /` block.
> 
> ```
> server{
>     # Port listen
>     listen 80;
> 
>     # DNS Record for catch request
>     server_name match.cs.white-gaming.fr;
> 
>     # Open block for process forward request
> location / {
>                 proxy_pass http://172.18.0.4;
>                 proxy_http_version 1.1;
>                 proxy_set_header Upgrade $http_upgrade;
>                 proxy_set_header Connection 'upgrade';
>                 proxy_set_header Host $host;
>                 proxy_cache_bypass $http_upgrade;
>     }
>     location /api/ {
>         proxy_pass http://172.18.0.3:3301; 
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection 'upgrade';
>         proxy_set_header Host $host;
>         proxy_cache_bypass $http_upgrade;
>    }
> }
> ```

hum, my initial nginx config have same format of your last 

initial
![image](https://user-images.githubusercontent.com/9698964/165966194-58d7168b-514b-4d34-9227-1bbbae2d0b13.png)

your last version
![image](https://user-images.githubusercontent.com/9698964/165966236-dd73b542-0819-46cf-9f7d-6d2a5ccd0a03.png)

my actual init
![image](https://user-images.githubusercontent.com/9698964/165966305-71f00398-821a-4a0a-9c15-40676a7f9842.png)

**Comment by Iwhite67** [comment]
![image](https://user-images.githubusercontent.com/9698964/165967080-9df89a05-6a9e-4dea-9f62-2348b2b3be09.png)

**Comment by PhlexPlexico** [comment]
Okay well that's a positive! It means the API is interacting properly!! So next up, this may be a bug bit I'm just confirming with a fresh database instance. Are you able to go create teams and whatnot?

**Comment by Iwhite67** [comment]
> Okay well that's a positive! It means the API is interacting properly!! So next up, this may be a bug bit I'm just confirming with a fresh database instance. Are you able to go create teams and whatnot?

no because he don't connect after steam

```services:
  get5db:
    image: yobasystems/alpine-mariadb
    container_name: get5db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=get5
      - MYSQL_USER=get5
      - MYSQL_PASSWORD=
    ports:
      - "3307:3306"
    networks:
      - get5

  g5api:
    image: ghcr.io/phlexplexico/g5api:latest
    depends_on:
      - get5db
    container_name: G5API
    volumes:
      - redisVol:/RedisFiles
    expose:
      - 3301
    environment:
      - PORT=3301
      - HOSTNAME=http://match.cs.white-gaming.fr
      - DBKEY=
      - STEAMAPIKEY=
      - SHAREDSECRET=
      - CLIENTHOME=http://match.cs.white-gaming.fr
      - APIURL=http://match.cs.white-gaming.fr/api/
      - SQLUSER=get5
      - SQLPASSWORD=
      - SQLPORT=3306
      - DATABASE=get5
      - SQLHOST=get5db
      - ADMINS=
      - SUPERADMINS=76561198033164185
      - REDISPASSWORD=
      - UPLOADDEMOS=true
    restart: unless-stopped
    networks:
```

on this server, i have mariadb on 3306

**Comment by PhlexPlexico** [comment]
So you already have a SQL database? You're going to need to change the following, or just use it's own database instance (probably easier?)

```yaml
environment:
      - PORT=3301
      - HOSTNAME=http://match.cs.white-gaming.fr
      - DBKEY=
      - STEAMAPIKEY=
      - SHAREDSECRET=
      - CLIENTHOME=http://match.cs.white-gaming.fr
      - APIURL=http://match.cs.white-gaming.fr/api/
      - SQLUSER=get5 # MAKE SURE THIS USER EXISTS
      - SQLPASSWORD= # I NEED A PASSWORD
      - SQLPORT=3306 
      - DATABASE=get5 # MAKE SURE THIS DATABASE EXISTS
      - SQLHOST=get5db # THIS HAS TO BE host.docker.internal
      - ADMINS=
      - SUPERADMINS=76561198033164185
      - REDISPASSWORD=
      - UPLOADDEMOS=true
```

Alternatively, if you wish to use the database that's in the compose file. just change `- SQLPORT=3306` to `- SQLPORT=3307`!

**Comment by Iwhite67** [comment]
i check because i have user get5 but in localhost, i will go change

`THIS HAS TO BE host.docker.internal` what is ?

**Comment by PhlexPlexico** [comment]
`host.docker.internal` redirects back to your host machine. I know you mentioned you are already running a MySQL database, which I assume is on the host machine and not another docker container, right? So we need to connect to that database. The host `get5db` will resolve to whatever Docker IP the container `get5db` is running.

**Comment by Iwhite67** [comment]
```yarn install v1.22.18
G5API     | [1/6] Validating package.json...
G5API     | [2/6] Resolving packages...
G5API     | success Already up-to-date.
G5API     | Done in 0.85s.
G5API     | yarn run v1.22.18
G5API     | $ MYSQL_FLAGS="-CONNECT_WITH_DB" db-migrate --env production --config config/production.json db:create get5
G5API     | Ignoring invalid configuration option passed to Connection: driver. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
G5API     | Ignoring invalid configuration option passed to Connection: redisHost. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
G5API     | Ignoring invalid configuration option passed to Connection: redisPort. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
G5API     | Ignoring invalid configuration option passed to Connection: redisTTL. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
G5API     | Ignoring invalid configuration option passed to Connection: redisPass. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
G5API     | [ERROR] AssertionError [ERR_ASSERTION]: ifError got unwanted exception: getaddrinfo ENOTFOUND host.docker.internal
G5API     |     at /Get5API/G5API/node_modules/db-migrate/lib/commands/db.js:17:12
G5API     |     at /Get5API/G5API/node_modules/db-migrate/lib/driver/index.js:95:9
G5API     |     at /Get5API/G5API/node_modules/db-migrate-mysql/index.js:518:14
G5API     |     at Connection.<anonymous> (/Get5API/G5API/node_modules/mysql2/lib/connection.js:775:13)
G5API     |     at Object.onceWrapper (node:events:514:26)
G5API     |     at Connection.emit (node:events:394:28)
G5API     |     at Connection._notifyError (/Get5API/G5API/node_modules/mysql2/lib/connection.js:236:12)
G5API     |     at Connection._handleFatalError (/Get5API/G5API/node_modules/mysql2/lib/connection.js:167:10)
G5API     |     at Connection._handleNetworkError (/Get5API/G5API/node_modules/mysql2/lib/connection.js:180:10)
G5API     |     at Socket.emit (node:events:394:28)
G5API     |     at emitErrorNT (node:internal/streams/destroy:157:8)
G5API     |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
G5API     |     at processTicksAndRejections (node:internal/process/task_queues:83:21)
G5API     |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
G5API     | error Command failed with exit code 1.
G5API     | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
G5API exited with code 1
```

![image](https://user-images.githubusercontent.com/9698964/165974503-bef8d844-62fc-4a00-8bff-dad7ad7286ef.png)

![image](https://user-images.githubusercontent.com/9698964/165974542-9b3dcecf-a5f9-4cea-8e94-c7d6da12ea1d.png)

**Comment by PhlexPlexico** [comment]
Okay, well it still launches and you were able to get to the database right? As you show, it did get inserted. Is there any logs on the API by any chance that are showing any GETs? `docker logs G5API` and try and load the main page :)

**Comment by Iwhite67** [comment]
```0|G5API  | GET /auth/steam 302 231.425 ms - 0
0|G5API  | ::ffff:172.18.0.1 - - [29/Apr/2022:15:29:08 +0000] "GET /auth/steam HTTP/1.1" 302 0 "http://match.cs.white-gaming.fr/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36 OPR/85.0.4341.72"
0|G5API  | GET /auth/steam/return?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198033164185&openid.identity=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198033164185&openid.return_to=http%3A%2F%2Fmatch.cs.white-gaming.fr%2Fapi%2F%2Fauth%2Fsteam%2Freturn&openid.response_nonce=2022-04-29T15%3A29%3A09ZylmDjJlh2wh7b6QAQoatX3cTPTY%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=fMRGs37VAfYY8MpeHIALeiHiyVc%3D 302 674.191 ms - 106
0|G5API  | ::ffff:172.18.0.1 - - [29/Apr/2022:15:29:10 +0000] "GET /auth/steam/return?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198033164185&openid.identity=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198033164185&openid.return_to=http%3A%2F%2Fmatch.cs.white-gaming.fr%2Fapi%2F%2Fauth%2Fsteam%2Freturn&openid.response_nonce=2022-04-29T15%3A29%3A09ZylmDjJlh2wh7b6QAQoatX3cTPTY%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=fMRGs37VAfYY8MpeHIALeiHiyVc%3D HTTP/1.1" 302 106 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36 OPR/85.0.4341.72"
```

**Comment by Iwhite67** [comment]
DevTools failed to load source map: Could not parse content for http://match.cs.white-gaming.fr/js/277.ae7d1617.js.map: Unexpected token < in JSON at position 0

**Comment by PhlexPlexico** [comment]
Hmm that's fine, could you try navigating to `http://match.cs.white-gaming.fr/api/teams` or something similar? When you logged in, did it store your username in the database?

**Comment by Iwhite67** [comment]
![image](https://user-images.githubusercontent.com/9698964/165977352-55c2dde6-7803-450a-ab71-9f4a4963726d.png)
![image](https://user-images.githubusercontent.com/9698964/165977425-d5b51269-8fff-4fb2-a4f8-2b97631ff0bb.png)

no username

**Comment by Iwhite67** [comment]
i put Iwhite in username, Teams is loading now

**Comment by PhlexPlexico** [comment]
Okay so if the /api/ call still isn't working, can you paste in your NGINX config again if you don't mind?

Thanks!

**Comment by PhlexPlexico** [comment]
Uhh you shouldn't put it in username because you don't want to use a local login if you're signing in through steam... Technically anyone could login with a blank password for your username then I think.

**Comment by Iwhite67** [comment]
> 

ok, so this is good, is working, steam has return and put into sql, i create manualy a team in sql and i can see

only actualy, the problem is, i can't connect

**Comment by PhlexPlexico** [comment]
Yeah, that would mean the API requests are still not working on the reverse proxy. Would you mind showing that NGINX config again, and see if we can spot anything off?

Thanks!

**Comment by Iwhite67** [comment]
```server{
    # Port listen
    listen 80;

    # DNS Record for catch request
    server_name match.cs.white-gaming.fr;

    # Open block for process forward request
location / {
        try_files $uri /index.html;
                proxy_pass http://172.18.0.3;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
}
        location /api/ {
        proxy_pass http://172.18.0.2:3301/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
   }
}
```

**Comment by Iwhite67** [comment]
![image](https://user-images.githubusercontent.com/9698964/165978933-09cf8094-35a4-4c0f-8bfc-ffbca566a0b5.png)

**Comment by PhlexPlexico** [comment]
And sorry, going to something like `match.cs.white-gaming.fr/api/matches` in a browser, does that return an empty array? It should just be a blank page with a message...

Thanks!

**Comment by Iwhite67** [comment]
![image](https://user-images.githubusercontent.com/9698964/165979348-ebf244de-d04f-49a3-ba57-1b8b8b429d2b.png)

**Comment by PhlexPlexico** [comment]
And is there any logs on the API that's making calls to that? If not, that may be the issue. Also, I'm just going to move this to a discussion since it may be easier to talk and less clog on an issue :)
