### ISSUE TITLE
[Request] Presets matches for bo3, bo5, bo7

### ISSUE THREAD

**Issue by rpkaul** [PhlexPlexico/G5V#153]
We already discussed on discord about this, I am creating the issues so we can track the status.
some tournament organizers don't use in-game (get5) veto and just do it outside on Paper/Discord or on any3rd party website ex - https://www.mapban.gg/en/ban/csgo

This is a good option if we can pre-configured matches via panel itself where we can choose team's maps pick and sides pick

example image - https://cdn.discordapp.com/attachments/979271257826676746/1004752512294862868/unknown.png

**Comment by PhlexPlexico** [comment]
I was thinking more about this, but you could just use seasons to adjust when it's a bo3/5/7. I feel that the maps shouldn't be static in any way as I feel teams won't always agree to have the same 3/5/7 maps. 

However, the side selection is something I need to add on as well, and will try and figure out something though. It would have to be done on both the front end and the API side.

**Comment by PhlexPlexico** [comment]
Okay, with the latest pushes to master, you can now choose where teams start with map_sides and disabling in game veto. Seasons also store these things too, so you can choose to have defaults for skip veto :) I think this should be good to close, and if there's any other issues, feel free to reopen this ticket!
