### ISSUE TITLE
[BUG] No Veto in page

### ISSUE THREAD

**Issue by Iwhite67** [PhlexPlexico/G5V#160]
Hello

i test new version, i have a problem with veto, i can view Players stats in game but not veto

![image](https://user-images.githubusercontent.com/9698964/192161227-86379c95-a707-40d2-93ce-f79d0275613b.png)
![image](https://user-images.githubusercontent.com/9698964/192161232-49b37e45-0a30-44cc-b2e2-27322e1d2669.png)
![image](https://user-images.githubusercontent.com/9698964/192161243-b36b2ff4-61d3-49f4-817e-744bb13b6e29.png)

**Comment by PhlexPlexico** [comment]
Can you please reproduce these on a public panel as well so I can further look at the database values and ensure it's nothing wrong with configurations? Thanks!

**Comment by Iwhite67** [comment]
After some test, some time on Ctrl f5, I have table, some time no

**Comment by Iwhite67** [comment]
> https://phlex.avidgamers.me/match/3931 If you try loading this one do you run into the same issue?
> 
> Thanks!

for me is good, is maybe my server

**Comment by PhlexPlexico** [comment]
It could be server performance. But this is something that should load as soon as the data is available. I think I can make a quick fix for this.

**Comment by PhlexPlexico** [comment]
Latest push should fix this. Should be available in the GHCR repos in about 10 minutes :)

**Comment by Iwhite67** [comment]
![image](https://user-images.githubusercontent.com/9698964/192566120-f6534ff6-2949-4e79-845d-ca1b90c723d5.png)
{"vetoes":[{"id":1,"match_id":2,"team_name":"Iwhite","map":"de_ancient","pick_or_veto":"ban"},{"id":2,"match_id":2,"team_name":"Radon","map":"de_overpass","pick_or_veto":"ban"},{"id":3,"match_id":2,"team_name":"Iwhite","map":"de_nuke","pick_or_veto":"ban"},{"id":4,"match_id":2,"team_name":"Radon","map":"de_vertigo","pick_or_veto":"ban"},{"id":5,"match_id":2,"team_name":"Iwhite","map":"de_mirage","pick_or_veto":"ban"},{"id":6,"match_id":2,"team_name":"Radon","map":"de_inferno","pick_or_veto":"ban"},{"id":7,"match_id":2,"team_name":"Decider","map":"de_dust2","pick_or_veto":"pick"}]}
nothing

**Comment by PhlexPlexico** [comment]
Oh, this may be due to the way the Server Sent Events are implemented. Check your logs on the API side as well to ensure the /stream location is being hit.

**Comment by Iwhite67** [comment]
![image](https://user-images.githubusercontent.com/9698964/192571961-46acc7ff-10bf-4323-bcca-b3757be18ce9.png)
i don't see vetoes/3/stream

**Comment by PhlexPlexico** [comment]
It's vetosides :) I've pushed out a fix for streams to see if that will fix the issue. Make sure you're using the latest version of G5WS as well, since that allows for sides to be chosen as well. Let me know if that works, thanks!

**Comment by Iwhite67** [comment]
Last version of WS


![image](https://user-images.githubusercontent.com/9698964/192573212-475a6162-c1e7-4744-9c06-8291822c7250.png)

![image](https://user-images.githubusercontent.com/9698964/192573339-d8fdf107-056b-4de6-966c-3904adf482b0.png)

![image](https://user-images.githubusercontent.com/9698964/192573436-252ac8d8-b238-4418-a542-9fa88a10f38b.png)

**Comment by PhlexPlexico** [comment]
The new update still hasn't pushed out to the registry yet, wait about 5 minutes before pulling. Thanks!

**Comment by Iwhite67** [comment]
yes i waiting, i just send screen for example

**Comment by PhlexPlexico** [comment]
Okay it should be up now :) try that and see if it works

**Comment by Iwhite67** [comment]
this is good, thanks
