### ISSUE TITLE
[Meta] Resuming development

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5V#176]
After today's announcement of resuming eBot development for CS2 after 5 years of being a stale project, I'd like to propose into consideration resuming development for G5V/G5API to support new CS2, if get5 is willing to continue to be updated for CS2.

**Comment by PhlexPlexico** [comment]
If get5 resumes development, these tools should always work, so long as the HTTP calls from get5 remain the same :)

**Comment by kubo6472** [comment]
Yes yes, I understand completely. Unfortunately, since we still need new servers managed somehow, and the whole SM ecosystem seems to be broken, I will be playing with eBot a bit more. If things will get moving again here, I'll be more than happy to return. In the meantime, let's keep this open for tracking the progress on the get5/sm side, since there seems to be quite a few things that need to be changed and fixed over there.

**Comment by xe1os** [comment]
@PhlexPlexico have a look at https://github.com/Lan2Play/PugSharp

It loads match config url (!ps_loadconfig <url>) which is same as csgo. 

Is it possible to configure G5V for the PugSharp plugin?

**Comment by PhlexPlexico** [comment]
No, unless it has the same HTTP calls. I'm not interested in trying to make the API work with other tools, as it would be a different project entirely.

**Comment by PhlexPlexico** [comment]
Considering this now is implemented in MatchZy, this can be closed since no further development is necessary from this side.
