### ISSUE TITLE
[Question] Prevent SteamID64 as required

### ISSUE THREAD

**Issue by mrc4tt** [PhlexPlexico/G5V#184]
Hi,

Is it possible on this G5V to set up SteamID64 as **NOT** required for setup matches, just teamname, without assigning SteamIDs64?

**Comment by PhlexPlexico** [comment]
The API does already allow this. You can create a team with no users on it and create a match with those teams.

**Comment by mrc4tt** [comment]
Alright, maybe I need to modify MatchZy before it's possible. ^

**Comment by mrc4tt** [comment]
Apologies for bumping this thread. 

Are you suggesting that the issue is caused by the Matchzy plugin? Specifically, I'm unable to select CT or T after starting a match on G5V without adding player names and SteamID64. Is that correct?

CC: @PhlexPlexico (Sorry for tagging)

**Comment by PhlexPlexico** [comment]
That would be a MatchZy feature. The API and front end do not control the game, short of sending rcon commands. It's up to the plugin to determine if it can allow empty teams.

Technically, on the API side for scrims, it can create a match with empty teams, then update the teams to include new players, then it will create and send the match JSON to the plugin via rcon.
