### ISSUE TITLE
No connect get5 in servers

### ISSUE THREAD

**Issue by lukasz922** [PhlexPlexico/G5V#27]
HI
i have a problem creating a match in get5 vue. After creating match in console i see to

i have sure bad plugin smx

![obraz](https://user-images.githubusercontent.com/50584055/98581480-d3a88000-22c1-11eb-9bab-f0b41c50d4e0.png)

**Comment by PhlexPlexico** [comment]
As I mentioned, this is a [G5API ](https://github.com/phlexplexico/G5API) problem. So please, report the bug there. And, I did provide the SMX that I have been using for testing that seems to work, so please use that instead.
[get5_apistats.zip](https://github.com/PhlexPlexico/G5V/files/5512718/get5_apistats.zip)
