### ISSUE TITLE
[Request] GoTV Button

### ISSUE THREAD

**Issue by lukasz922** [PhlexPlexico/G5V#30]
Hi,
Old get5-web  had a button GOTV  maybe  think  new get5vue also had button GOTV ?? 

It would be enough  added this GOTV port durring added  New server

**Comment by PhlexPlexico** [comment]
GoTV ports have been introduced into the API and the front end will now show a GoTV button if a user wishes to connect to it (must be signed in first).

**Comment by lukasz922** [comment]
admin can see too ? I have uploaded the current get5 i dont see button GOTV Button

**Comment by PhlexPlexico** [comment]
My bad - the match must be running and there must be an IP:

https://github.com/PhlexPlexico/G5V/blob/232d9f4f136810047047de9ac5678b907897032d/src/components/MatchInfo.vue#L63

After that, there's a check to see if the tv port is null:

https://github.com/PhlexPlexico/G5V/blob/232d9f4f136810047047de9ac5678b907897032d/src/components/MatchInfo.vue#L85

That being said I haven't tested this much, if at all. But it should appear beside the connect button.

**Comment by lukasz922** [comment]
i will test today for GOTV , i will start the match .i  will check to see GOTV buttom. I back more info

**Comment by PhlexPlexico** [comment]
Fixed in latest push.

**Comment by lukasz922** [comment]
Confirm   GOTV button 
![image](https://user-images.githubusercontent.com/50584055/104039179-553f6000-51d6-11eb-8956-e3b52c27b8b3.png)
