### ISSUE TITLE
[Enhancement] Adjust Team Table for Mobile

### ISSUE THREAD

**Issue by PhlexPlexico** [PhlexPlexico/G5V#4]
Right now in the data tables, it isn't structured very well to provide a clean mobile view. This is an eventual task to fix because once one table has been fixed, the rest will be easy to update.

**Comment by PhlexPlexico** [comment]
The only one to really be changed is the user table. The profile images seem to really goof up the table.

**Comment by PhlexPlexico** [comment]
Everything else seems to be mobile friendly enough with how it was implemented, now it's just the team table really taking a toll on mobile setups. This is mainly due to the image not obeying the data table. Will need to look into and adjust as needed.

**Comment by TandelK** [comment]
@PhlexPlexico Can we make Player Stats with First Column of their Steam Names as Statics and other move. Here is the example i am talking about 
https://codepen.io/paulobrien/pen/gWoVzN

**Comment by PhlexPlexico** [comment]
And where exactly would you want this? In the match table? Because right now that's the only place where player stats are.

And that being said, that data table is already held together by positive thoughts and best wishes, with the grouping and all. I believe it still looks good on mobile since the orientation switches? But I'll take a look into it.

**Comment by PhlexPlexico** [comment]
With the use of breakpoints I was able to get the team table to look a bit cleaner on mobile. IF you're an admin, you won't see any header information aside from teh buttons, and if you're a user, all you will see is the team name, since nothing else really fits.
