### ISSUE TITLE
[Request] Refresh Score Updates

### ISSUE THREAD

**Issue by PhlexPlexico** [PhlexPlexico/G5V#42]
During a match, (or even on the front page, if it's not too intensive) it would be nice to see some updates to the scorecards when a match is ongoing. This can be done with a timer that just calls the API and updates the data within the table.

Since we're not using something like websockets (which is something I should look into if I ever want a live-update of scores?) we can just poll during an average match time, say around 1 minute to refresh data, and give users a refresh button that would pull the data, and enable that pull after 30 seconds, so people don't just mash refresh.

**Comment by lukasz922** [comment]
Good idea  I missed that : )

**Comment by PhlexPlexico** [comment]
Users will now see a nice message (if people choose to translate!) that will inform them the data in that match will refresh every 60 seconds. I chose not to include a button because people can just choose to refresh the page, and it was having some issues with keeping the additional headers open when there was a countdown on the page.
