### ISSUE TITLE
[Request] Adding BO2 as a match type

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5V#50]
How hard would it be to go into files and add BO2 as a match time both in the season and match creation pages?

**Comment by PhlexPlexico** [comment]
Honestly? I'm not too sure haha. I don't think there's any limitation on the API, so it would be as simple as adding in the option here:

https://github.com/PhlexPlexico/G5V/blob/4df9086c0c7baf7884d8530d4cf0e65bbce0e382/src/components/NewMatchForm.vue#L96-L109


And just add in a best of two. However, I'm not sure how that would effect the rules based on the map pool selection..,.

**Comment by PhlexPlexico** [comment]
Okay this is done and now seasons and matches can now be set to BO2. You weren't the first one asking so please update accordingly :)

**Comment by kubo6472** [comment]
Just upgraded my prod panel to master from release. Gotta test it later today. Thank you so so so much for this fast feature addon.

**Comment by PhlexPlexico** [comment]
Hey @kubo6472 just wanted to touch base after a few days - is the BO2 setup working as it should? I know another org that wants to use it but don't feel confident enough until I get some more testers on it!

Thanks!

**Comment by kubo6472** [comment]
From my small testing, everything works alright. Since the league has not started yet it was not battle-tested that hard.

**Comment by PhlexPlexico** [comment]
No worries, that's confirmation enough for me! Thanks!
