### ISSUE TITLE
[Request] Matches Participated In View

### ISSUE THREAD

**Issue by PhlexPlexico** [PhlexPlexico/G5V#52]
Was talking with a user who was using the web panel and was confused why users couldn't see the matches they were a part of. This sparked interest in creating a new page that would replace the current "My Matches" page with matches that users are a part of, and another page that is "My Created Matches" that would be the matches that a user created.

**Comment by lukasz922** [comment]
Hi, 
do you think  by added bookmark servers in list matches ??

**Comment by lukasz922** [comment]
hi do you think  added bookmars server ??

![image](https://user-images.githubusercontent.com/50584055/113484333-0d179d00-94a8-11eb-9385-d3ba1dfbe1be.png)

**Comment by PhlexPlexico** [comment]
Sorry, but is this not the purpose of the "My Servers" link? I don't understand the need for "bookmarking" servers. Also, I believe this is completely unrelated to the issue above.

**Comment by PhlexPlexico** [comment]
I was thinking more about this - and if you wanted to see the recent played matches, you could just navigate to your user profile to see the top 5. Is that not usually good enough?

**Comment by PhlexPlexico** [comment]
There's been no response to this, but I think this can also go into #116 and just have the recent matches paginate on the user page as well.
