### ISSUE TITLE
[Feature Request] Toggle Button for My Servers/All Servers

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5V#59]
Can we get "all servers" when a server is public in a list?

**Comment by PhlexPlexico** [comment]
I just avoided putting this in the sidebar since I didn't want to clog it up too much - there actually does this: `/servers` should allow you to view all yours/public servers.

**Comment by kubo6472** [comment]
Thank you. Didn't know that. That brings up a question, if a setting that would toggle everything between "my" and "all" and just keeping one of the kind at a time in the menu?

**Comment by PhlexPlexico** [comment]
I can see what I can do for a toggle button that will show "My servers" and "My/Public Servers" :)
