### ISSUE TITLE
404 on subpages

### ISSUE THREAD

**Issue by mLgz0rn** [PhlexPlexico/G5V#61]
So I finally got everything up and running.
But whenever I go to a subpage it returns 404 even though I can see the page the first time I go to it.

example https://gather.mikl.ml works without any issues but https://gather.mikl.ml/matches dosnt.
But If I go to the pages using the menu from the main page I can see them, but the api still returns 404 and if I refresh the page I also see this 404 error.

```
::ffff:127.0.0.1 - - [29/Apr/2021:08:08:07 +0000] "GET /isLoggedIn HTTP/1.1" 304 - "https://gather.mikl.ml/matches" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"
GET /matches 404 8.318 ms - 31

::ffff:127.0.0.1 - - [29/Apr/2021:08:08:07 +0000] "GET /matches HTTP/1.1" 404 31 "https://gather.mikl.ml/matches" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"

```

I'm running the website part through nginx, and I have also set up the stuff for the reverse proxy.

Kind regards

**Comment by PhlexPlexico** [comment]
Hi!

There's actually a little bit of configuration needing to be done on your NGINX instance then. I've highlighted some of the important areas for setup in the wiki: https://github.com/PhlexPlexico/G5V/wiki/Reverse-Proxy-Setup-with-NGINX

That should fix the problems you're having!
Thanks!

**Comment by mLgz0rn** [comment]
Hey again!

Thanks for helping me in the right direction.
I finally got it working by disabling php for that particular subdomain, I'm running my website through a webpanel "froxlor" and it was adding this to the vhost when php was enabled

```
	location / {
		index index.php index.html index.htm;
		try_files $uri $uri/ @rewrites;
	}

	location @rewrites {
		rewrite ^ /index.php last;
	}
```
And I'm pretty sure that was the cause of the issue :D

**Comment by PhlexPlexico** [comment]
Ahhh yeah, I can definitely see that being an issue! My current setup is an NGINX reverse proxy to a docker container, which then has another NGINX instance... I had spent far too long with a buddy of mine trying to figure out why it wasn't working the way it should. Glad to hear you got it fixed! I will add this to the FAQ in the wiki!

Thanks!

**Comment by shaikhnedab** [comment]
Getting exactly same error but on apache2 server.
is there any workaround for apache2 server?

**Comment by PhlexPlexico** [comment]
Try adding `retry=0` to the end of the `ProxyPass` line that may fix it.

**Comment by shaikhnedab** [comment]
tried and still getting same error.
```
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
	ServerName match.kebabnation.xyz
    DocumentRoot /var/www/G5V/dist
  ProxyRequests on

        ProxyPass /api  http://match.kebabnation.xyz:3301 retry=0
        ProxyPassReverse /api http://match.kebabnation.xyz:3301 retry=0

</VirtualHost>
```

**Comment by PhlexPlexico** [comment]
Then I'm not too sure, you may have to google around since this seems to be a common issue for anyone using reverse proxies. I unfortunately don't have experience with apache2, sorry!

**Comment by PhlexPlexico** [comment]
https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxyerroroverride

I think you may have to put `ProxyErrorOverride off` as well, that may fix it?

**Comment by shaikhnedab** [comment]
tried but still no luck
```
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    ServerName match.kebabnation.xyz
    DocumentRoot /var/www/G5V/dist
    ProxyRequests on
    ProxyErrorOverride off

        ProxyPass /api  http://match.kebabnation.xyz:3301 retry=0
        ProxyPassReverse /api http://match.kebabnation.xyz:3301 retry=0

</VirtualHost>
```

**Comment by shaikhnedab** [comment]
migrated to nginx and everything is working as expected. thanks for your support
