### ISSUE TITLE
Tried moving to Caddy, now API is unreachable

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5V#65]
![image](https://user-images.githubusercontent.com/26146502/119569222-bb580880-bdae-11eb-9dc7-51165c7bed91.png)

I started getting these errors on the API. Is there any way to force an SSL cert onto the API?

**Comment by PhlexPlexico** [comment]
If it's an API error, there should be some more information in the logs. Since it's returning a 500, I would assume there's a configuration error on your Caddy setup.

**Comment by kubo6472** [comment]
I changed the API port and now it works. Just wanted to let you know I fixed it and only then I noticed your response. Thanks.
