### ISSUE TITLE
Cancelling match

### ISSUE THREAD

**Issue by EestiParim** [PhlexPlexico/G5V#67]
Hey, Thanks for such a great project!

I was trying out test enviorment- https://phlex.avidgamers.me/ and ran into issue where my server was wrongly configured, and it gave error, but still it created match, and now there are 4 matches with same teams, and I cant find way to delete them. When I try to delete server, it says I need to delete matches before 
attempting it, but I cant find how I can delete those. 

![image](https://user-images.githubusercontent.com/8903439/122573873-b86fd100-d057-11eb-80c9-f2c57deb8d4c.png)

**Comment by PhlexPlexico** [comment]
Hey! 

Even if the server still fails it will assign the match. However, if you click into the match ID, for example [this](https://phlex.avidgamers.me/match/379) while logged in, you should see a button for Admin Options. If you hover over it, you should be able to see "Cancel Match"
![image](https://user-images.githubusercontent.com/3514085/122584614-caca1a80-d017-11eb-8c83-2787e7e7ecf2.png)

**Comment by EestiParim** [comment]
Hey! Huge thanks for fast reply!

I feel a bit confused still, I searched for admin options, even let my friend use my account and see, but I cant find those admin options, I add few images aswell. 
![image](https://user-images.githubusercontent.com/8903439/122624540-5049db00-d0a9-11eb-812d-8ef8ba42d9cd.png)
![image](https://user-images.githubusercontent.com/8903439/122624549-563fbc00-d0a9-11eb-9438-6c6f71d88200.png)

**Comment by PhlexPlexico** [comment]
Oh! I suppose I disable it for anyone that isn't a registered admin. I can go ahead and cancel those matches if you would like :) maybe something to add as a feature to allow those basic commands.

**Comment by PhlexPlexico** [comment]
Okay, button should now show up for match owners on the web panel. Going to go ahead and close this now, since I cancelled your matches as well :)

thanks!
