### ISSUE TITLE
Wrong match config generated by G5V

### ISSUE THREAD

**Issue by hoan111** [PhlexPlexico/G5V#69]
Hello!
I'm using G5V and G5API to host a tournament. When I created a BO3 match, players on the game server can veto BO3, but the veto controller doesn't let them choose a side to play. And after the veto process, Get5 tell them "ready to knife for sides". It must be in the LIVE state after ready, not knife round. I checked the match config has been sent to the game server, and I see `"side_type":"default" ` instead of `"side_type":"standard"`. 
Please help me check this. Thank you!
![image](https://user-images.githubusercontent.com/32768392/128605693-e5e669f4-3af4-481b-82f2-2bfc74b1b763.png)

**Comment by PhlexPlexico** [comment]
Hmm, are you able to look in the database to see the values? When creating a match, could you select "never knife" then select "standard" again? I think that may be a form issue having a "default" setting because nowhere in G5API or G5V does it set default.

Thanks!

**Comment by hoan111** [comment]
This in the database
![image](https://user-images.githubusercontent.com/32768392/128607789-cf5547d3-3c88-4687-9558-d4cf0d98ed9b.png)

**Comment by PhlexPlexico** [comment]
Yeah - looking between wherever it's checked it's set as "standard" if given null values. I think it's the veto radio buttons having "default" as the initial value, even though "standard" is selected. Please try creating a match with selecting something else, then select the one you wish to have, that should fix it?

**Comment by hoan111** [comment]
Still not work :(

**Comment by PhlexPlexico** [comment]
Are you selecting a season as well?

**Comment by hoan111** [comment]
> Are you selecting a season as well?

Not yet. I only want to create a match without creating a season

**Comment by PhlexPlexico** [comment]
Yeah I'm not sure what could be the issue. I'm not able to reproduce either. Would you mind trying to reproduce the steps on the public panel?

**Comment by hoan111** [comment]
> Yeah I'm not sure what could be the issue. I'm not able to reproduce either. Would you mind trying to reproduce the steps on the public panel?

I tried to reproduce it on the public panel. The public panel worked correctly. Currently, I'm using the latest commit of G5V
