### ISSUE TITLE
[Feature] Match Creation

### ISSUE THREAD

**Issue by PhlexPlexico** [PhlexPlexico/G5V#8]
I need a space to write out some of the "must-haves" for creating a match. Right now, there is the ability to have a match that does not have a server assigned. 

- Should we allow matches with no servers to be assigned?
- Is there a way we should take care of vetoes on site? Or stick with in-game?
- How do we handle default CVARs if a Season/Tournament is chosen?

I believe this should be completed after Seasons/Tournaments is integrated, as it does play a part in how the match gets built.

**Comment by lukasz922** [comment]
Should we allow matches with no servers to be assigned? 
 AD
I think the match should be assigned to a specific server
Match = One Server 

Maybe information when creating a match with the server busy

**Comment by PhlexPlexico** [comment]
That's what I was thinking too. I think the reason I left the API open-ended (can create matches without servers) was to allow the use of discord bots, and various other tools to create matches before assigning a server. 

There's also an option in the matches to switch the assigned server to a new one as well, that way if a server is not working or is laggy, you are able to swap servers and continue playing.

However I think you're right, on creation on the panel there should be the requirement of a server to be selected.

Thanks for the input :)

**Comment by PhlexPlexico** [comment]
Match creation todos:

- [ ] Select A Server, or create
- [ ] Select season
- [ ] Fill out match details
- [ ] Default details if exist.
- [ ] Send out create match POST call to API.

**Comment by PhlexPlexico** [comment]
This is now completed. Next step is to get a proper representation of a match in progress (and connect buttons, etc).

**Comment by hoan111** [comment]
Hmmm, I think you should make the user can change full match details (I mean no default value). 
Example: I want to change `min_players_to_ready` but G5V doesn't support this (`Default value` of this is now set to` 5`). In case, players don't have enough 5 players to start but they want to map veto first to save their time, they can use the command !forceready to do that. But now `min_players_to_ready` is set to `5`, they cannot do that.
![image](https://user-images.githubusercontent.com/32768392/99360474-3661d300-28e3-11eb-97d1-543b5a483c5f.png)
![image](https://user-images.githubusercontent.com/32768392/99361661-03b8da00-28e5-11eb-806a-155631844f0b.png)

**Comment by PhlexPlexico** [comment]
So the reason I removed this is because it wasn't even implemented in the first place. There was no way to tell (between my fork of get5-web, G5API, and this) how many players were needed to forceready a match. I believe there was a few hacky changes here and there to make it work. I'll look into it, and was thinking of changing the players per team to a slider anyways.

**Comment by PhlexPlexico** [comment]
Also, this change has been made.

**Comment by hoan111** [comment]
Thank you! I tested and it's worked!
